Fix schellcheck warnings & unify installer script

diff --git a/.chezmoitemplates/utils/logger.sh.tmpl b/.chezmoitemplates/utils/logger.sh.tmpl
--- a/.chezmoitemplates/utils/logger.sh.tmpl
+++ b/.chezmoitemplates/utils/logger.sh.tmpl
@@ -1,35 +1,28 @@
+# chezmoi:template:left-delimiter="#{{" right-delimiter=}}
 log_success() {
   echo -e "\033[0;32m✓ [Success]: \033[0m $*"
 }
 
 log_info() {
-  {{- if ge .logLevel 1 }}
-    echo -e "\033[0;34mℹ [Info]: \033[0m $*"
-  {{- else }}
-    return
-  {{- end }}
+#{{- if ge .logLevel 1 }}
+  echo -e "\033[0;34mℹ [Info]: \033[0m $*"
+#{{ else }} :; #{{ end -}}
 }
 
 log_warning() {
-  {{- if ge .logLevel 2 }}
-    echo -e "\033[0;33m⚠ [Warning]: \033[0m $*"
-  {{- else }}
-    return
-  {{- end }}
+#{{- if ge .logLevel 2 }} 
+  echo -e "\033[0;33m⚠ [Warning]: \033[0m $*"
+#{{ else }} :; #{{ end -}}
 }
 
 log_error() {
-  {{- if ge .logLevel 3 }}
-    echo -e "\033[0;31m✗ [Error]: \033[0m $*" >&2
-  {{- else }}
-    return
-  {{- end }}
+#{{- if ge .logLevel 3 }} 
+  echo -e "\033[0;31m✗ [Error]: \033[0m $*" >&2
+#{{ else }} :; #{{ end -}}
 }
 
 log_debug() {
-  {{- if ge .logLevel 4 }}
-    echo -e "\033[0;90m? [Debug]: \033[0m $*"
-  {{- else }}
-    return
-  {{- end }}
+#{{- if ge .logLevel 4 }}
+  echo -e "\033[0;90m? [Debug]: \033[0m $*"
+#{{ else }} :; #{{ end -}}
 }
diff --git a/dot_bashrc.tmpl b/dot_bashrc.tmpl
--- a/dot_bashrc.tmpl
+++ b/dot_bashrc.tmpl
@@ -59,7 +59,7 @@ alias tree="eza -ghoMT --smart-group --git --no-time --no-permissions --group-di
 #{{- $bat := "bat" -}}
 #{{- if eq .deviceConfig.osType "ubuntu" -}}
 #{{-    $bat = "batcat" -}}
-#{{- end -}}
+#{{- end }}
 
 # shellcheck disable=SC2139,SC2154,SC2250
 alias cat="#{{ $bat }} -p"
@@ -72,6 +72,7 @@ else
 fi
 
 #{{ if ne .deviceConfig.installType "termux" -}}
+alias sudo="sudo "
 alias ctl="systemctl"
 
 #{{ end -}}
@@ -90,9 +91,9 @@ help() {
 
 if [[ -d "#{{ .chezmoi.sourceDir }}/extras" ]]; then
   for file in "#{{ .chezmoi.sourceDir }}/extras"/*; do
-    if [[ -f "$file" ]]; then
+    if [[ -f "${file}" ]]; then
       # shellcheck disable=SC1090
-      . "$file"
+      . "${file}"
     fi
   done
 fi
@@ -111,12 +112,12 @@ command_not_found_handle() {
   local cmd="$1"
   shift
 
-  if command -v "$cmd.exe" >/dev/null 2>&1; then
-    "$cmd.exe" "$@"
+  if command -v "${cmd}.exe" >/dev/null 2>&1; then
+    "${cmd}.exe" "$@"
     return
   fi
 
-  echo "command not found: $cmd" >&2
+  echo "command not found: ${cmd}" >&2
   return 127
 }
 
@@ -140,6 +141,8 @@ while read -r line; do
   fi
 done < <(alias -p)
 
-#{{ if eq (env "XDG_SESSION_DESKTOP") "GNOME" -}}
+#{{- if eq (env "XDG_SESSION_DESKTOP") "GNOME" }}
+
 alias logout="gnome-session-quit --no-prompt"
+
 #{{- end }}
